import Head from "next/head";
import Layout from "../components/Layout";
import Header from "../components/header";
import Footer from "../components/footer";
import Banner from "../components/banner";
import NavigationBar from './../components/navbar';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Folk Print</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar/>
    </div>
  );
}
